name: BlockHunt
main: ru.boomearo.blockhunt.BlockHunt
version: 0.1
author: BoomEaro
description: blockhunt
api-version: 1.13
depend: [FastAsyncWorldEdit, GameControl, ProtocolLib, LibsDisguises, LangHelper, MenuInv, Board, ServerUtils, AdvEco, ViaVersion]
commands:
  blockhunt:
    usage: /blockhunt
    aliases: [bh]
    description: blockhunt